


def build(bld):    
    obj = bld.create_ns3_program('vanet-highway-test', ['core'])
    obj.source = [
	'My_Simulation-IoV.cc',
	'Highway.cc',
	'Controller.cc',
	'Vehicle.cc',
	'Obstacle.cc',
	'Model.cc',
	'LaneChange.cc',
	]



